name: Publish Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: bufbuild/buf-setup-action@v1.8.0
        with:
          version: latest

      - name: Install protoc-gen-doc
        run: go install github.com/pseudomuto/protoc-gen-doc@latest

      - name: Generate buf
        run: buf generate --template buf.gen-web.yaml

      - name: Build website
        run:  cd website && npx docusaurus generate-proto-docs && npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: webpage/build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        
        
